

drop table if exists companies;
create table companies (
    id bigint generated by default as identity primary key,
    inserted_at timestamptz default timezone('utc', now()) not null,
    name text
);

create table jobs (
    id bigint generated by default as identity primary key,
    company_id bigint not null references companies(id),
    name text,
    description text
);